drop table account;
create table account (
    id bigint generated by default as identity primary key,
    username varchar(32) default '',
    password varchar(32) default ''
);

insert into account (username, password) values
('admin', 'admin'),
('user', 'user');
