drop table account;
drop table role;

create table account (
    id bigint generated by default as identity primary key,
    username varchar(32) default '',
    password varchar(32) default '',
    create_time date default null,
    update_time date default null,
    balance decimal(10, 2) default 0.00
);

insert into account (username, password, create_time, balance) values
('admin', 'admin123', '2020-01-01 00:00:00', 1000.00),
('user', 'user123', '2024-05-02 00:00:00', 100.00),
('guest', 'guest123', '2022-03-03 00:00:00', 10.00),
('tang', 'tang123', '2019-06-01 00:00:00', 1.00),
('jeo', 'jeo123', '2024-07-01 00:00:00', 0.10);

create table account_role (
    account_id bigint,
    role_id bigint,
    primary key (account_id, role_id)
);

insert into account_role (account_id, role_id) values
(1, 1),
(2, 2),
(2, 3),
(3, 3),
(4, 2),
(5, 3);

create table role (
    id bigint primary key,
    name varchar(32) default ''
);

insert into role (id, name) values
(1, 'admin'),
(2, 'user'),
(3, 'guest');
