drop table account;
drop table role;

create table account (
    id bigint generated by default as identity primary key,
    username varchar(32) default '',
    password varchar(32) default '',
    create_time date default null,
    update_time date default null,
    balance decimal(10, 2) default 0.00
);

insert into account (username, password, create_time, balance) values
('admin', 'admin', '2020-01-01 00:00:00', 1000.00),
('user', 'user', '2024-05-02 00:00:00', 100.00),
('guest', 'guest', '2022-03-03 00:00:00', 10.00),
('tang', 'tang', '2019-06-01 00:00:00', 1.00),
('jeo', 'jeo', '2024-07-01 00:00:00', 0.10);

create table role (
    id bigint primary key,
    name varchar(32) default ''
);

insert into role (id, name) values
(1, 'admin'),
(2, 'user'),
(3, 'guest');
