package com.tang.kite.executor.defaults

import com.tang.kite.executor.ExecutionResult
import com.tang.kite.executor.Executor
import com.tang.kite.sql.statement.BatchSqlStatement
import com.tang.kite.sql.statement.SqlStatement
import com.tang.kite.transaction.Transaction
import com.tang.kite.utils.Statements
import com.tang.kite.utils.resultset.ResultSetHandlers
import org.slf4j.LoggerFactory
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

/**
 * @author Tang
 */
class DefaultExecutor(private val transaction: Transaction) : Executor {

    private val logger = LoggerFactory.getLogger(DefaultExecutor::class.java)

    override fun getConnection(): Connection {
        return transaction.getConnection()
    }

    override fun <T> count(statement: SqlStatement, type: Class<T>): ExecutionResult<Long> {
        val connection = getConnection()
        val preparedStatement = connection.prepareStatement(statement.sql)
        statement.setValues(preparedStatement)
        var executionTime = 0L
        var mappingTime = 0L
        val executeResult = executeTemplate(
            preparedStatement = preparedStatement,
            connection = connection,
            statementType = "count",
            runAction = {
                val executionStartTime = System.nanoTime()
                val resultSet = it.executeQuery()
                executionTime = System.nanoTime() - executionStartTime
                val mappingStartTime = System.nanoTime()
                val result = ResultSetHandlers.getCount(resultSet)
                mappingTime = System.nanoTime() - mappingStartTime
                result
            },
            defaultValue = 0L
        )
        return ExecutionResult(executeResult, executionTime, mappingTime)
    }

    override fun <T> query(statement: SqlStatement, type: Class<T>): ExecutionResult<List<T>> {
        val connection = getConnection()
        val preparedStatement = connection.prepareStatement(statement.sql)
        statement.setValues(preparedStatement)
        var executionTime = 0L
        var mappingTime = 0L
        val executeResult = executeTemplate(
            preparedStatement = preparedStatement,
            connection = connection,
            statementType = "query",
            runAction = {
                val executionStartTime = System.nanoTime()
                val resultSet = it.executeQuery()
                executionTime = System.nanoTime() - executionStartTime
                val mappingStartTime = System.nanoTime()
                val result = ResultSetHandlers.getList(resultSet, type)
                mappingTime = System.nanoTime() - mappingStartTime
                result
            },
            defaultValue = mutableListOf()
        )
        return ExecutionResult(executeResult, executionTime, mappingTime)
    }

    override fun update(statement: SqlStatement, parameter: Any): ExecutionResult<Int> {
        val connection = getConnection()
        val autoGeneratedKeys = getAutoGeneratedKeys(statement.sql, parameter)
        val preparedStatement = connection.prepareStatement(statement.sql, autoGeneratedKeys)
        statement.setValues(preparedStatement)
        var executionTime = 0L
        val executeResult = executeTemplate(
            preparedStatement = preparedStatement,
            connection = connection,
            statementType = "update",
            runAction = {
                val executionStartTime = System.nanoTime()
                val resultSet = it.executeUpdate()
                executionTime = System.nanoTime() - executionStartTime
                resultSet
            },
            alsoAction = { ResultSetHandlers.setGeneratedKey(statement.sql, it, parameter) },
            defaultValue = 0
        )
        return ExecutionResult(executeResult, executionTime)
    }

    override fun update(batchSqlStatement: BatchSqlStatement, parameters: List<Any>): ExecutionResult<Int> {
        val connection = getConnection()
        val autoGeneratedKeys = getAutoGeneratedKeys(batchSqlStatement.sql, parameters.first())
        val preparedStatement = connection.prepareStatement(batchSqlStatement.sql, autoGeneratedKeys)
        for (parameter in batchSqlStatement.parameters) {
            Statements.setValues(preparedStatement, parameter)
            preparedStatement.addBatch()
        }
        var executionTime = 0L
        val executeResult = executeTemplate(
            preparedStatement = preparedStatement,
            connection = connection,
            statementType = "batch update",
            runAction = {
                val executionStartTime = System.nanoTime()
                val resultSet = it.executeBatch().sum()
                executionTime = System.nanoTime() - executionStartTime
                resultSet
            },
            alsoAction = { ResultSetHandlers.setGeneratedKey(batchSqlStatement.sql, it, parameters) },
            defaultValue = 0
        )
        return ExecutionResult(executeResult, executionTime)
    }

    override fun commit() {
        transaction.commit()
    }

    override fun rollback() {
        transaction.rollback()
    }

    override fun close() {
        transaction.close()
    }

    private fun <R> executeTemplate(
        preparedStatement: PreparedStatement,
        connection: Connection,
        statementType: String,
        runAction: (PreparedStatement) -> R,
        alsoAction: (PreparedStatement) -> Unit = {},
        defaultValue: R
    ): R {
        return runCatching {
            runAction(preparedStatement)
        }.onFailure {
            it.printStackTrace()
            connection.rollback()
        }.also {
            alsoAction(preparedStatement)
            logger.debug("Closing {} prepared statement [{}]", statementType, preparedStatement)
            preparedStatement.close()
        }.getOrDefault(defaultValue)
    }

    private fun getAutoGeneratedKeys(sql: String, parameter: Any): Int {
        return if (ResultSetHandlers.hasGeneratedKey(sql, parameter)) {
            Statement.RETURN_GENERATED_KEYS
        } else {
            Statement.NO_GENERATED_KEYS
        }
    }

}
