package com.tang.kite.datasource

import com.tang.kite.io.Resources
import com.tang.kite.datasource.entity.DataSourceAccount
import com.tang.kite.session.factory.SqlSessionFactoryBuilder
import com.tang.kite.datasource.mapper.DataSourceAccountMapper
import kotlin.test.Test

/**
 * @author Tang
 */
class MultipleDatasourceTest {

    companion object {

        private val resource = Resources.getResourceAsStream("kite-multiple-datasource-config.yml")

        val sqlSessionFactory = SqlSessionFactoryBuilder().build(resource)

        val sqlDsl = """
        create table account (
            id bigint generated by default as identity primary key,
            username varchar(32) default '',
            password varchar(32) default ''
        );
    """.trimIndent()

        fun insertAccounts(dataSourceKey: String) {
            DataSourceManager.with(dataSourceKey) {
                val session = sqlSessionFactory.openSession()
                val accountMapper = session.getMapper(DataSourceAccountMapper::class)
                session.getConnection().use { connection ->
                    connection.createStatement().use { it.execute(sqlDsl) }
                }
                for (i in 1..5) {
                    accountMapper.insert(
                        DataSourceAccount(
                            username = "user-$dataSourceKey-$i",
                            password = "password$i"
                        )
                    )
                }
                session.commit()
                session.close()
            }
        }

        init {
            insertAccounts("ds1")
            insertAccounts("ds2")
        }

    }

    private fun checkDataSourceKey(dataSourceKey: String) {
        val sqlSession = sqlSessionFactory.openSession()
        val accountMapper = sqlSession.getMapper(DataSourceAccountMapper::class)
        val accounts = accountMapper.select()
        accounts.forEach { assert(it.username?.startsWith("user-$dataSourceKey") == true) }
        sqlSession.close()
    }

    @Test
    fun testDefaultDatasource() {
        checkDataSourceKey("ds1")
    }

    @Test
    fun testDataSourceContext() {
        checkDataSourceKey("ds1")
        DataSourceManager.with("ds2") {
            checkDataSourceKey("ds2")
            DataSourceManager.with("ds1") {
                checkDataSourceKey("ds1")
            }
            checkDataSourceKey("ds2")
        }
        checkDataSourceKey("ds1")
    }

}
